#+TITLE: Getting started
#+STARTUP: overview
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="finishing-touches.css"/>

* TODO updade portage build

=emerge sci-visualization/gnuplot=

add the following to =/etc/portage/package.use=

=media-libs/gd-2.0.35-r4=

* Tutorial

how to go about changing the keyboard

you can open up pdfs and other media using =emacscliente= when downloading.

** TODO emacs quick navigation

see steve yegge's effective emacs

using dired, M-o f, org and url's from emacs

i-search, ace jump, rename symbol, symbol navigate 

** TODO update C-t ? and the rest of the help keys to do something else useful

This tutorial will take you probably an hour to complete, so set aside some time.

For now you'll need to learn how to use stumpwm, emacs & conkeror. Emacs and conkeror have their own tutorials both accessible via =C-h t= and user manuals accessible via =C-h i=. =C-t ?= should suffice for stumpwm.

wifi settings can be accessed via the "network" command

=C-t h= will always send you back here.

=describe-key=
=describe-command=

** Browser
** Stumpwm

The simplest way to navigate is using C-t arrow keys!

** Lessons system

=C-t m= opens the kgraph (knowledge graph).

** Dashboard
   
Masamune's concept of `habits' is essentially the english defintion, activities that one wants to repeat over some timeframe. Habits can be installed though the masamune code repository avalible through the stumpw command `repository'. The test habit can be removed by selecting the option 'delete habit' avalible on right click. Masamune's habits automatically gather data about your usage habits and informs you of this. In general masamune collects a great deal of data - this information is stored locally for your convenience and not sent to any parties (read code to verify this yourself). Some analysis is done by default for the dashboard.

All data collection is disabled by default, but can be turned on. It is recommended that you see the documentation =Security= before doing this.

=C-t d= Opens the dashboard.

Masamune will optionally open this interface when it detects you wake up to give you an overview of your day.

CLIM is neat. Try running the following at the listener, which you can open by running =(mm::listener)= at the REPL.

#+BEGIN_SRC
(loop for i from 0 to 10 do (draw-circle* *standard-output* 300 300 (expt i 3) :filled nil :ink +blue+ :line-thickness (expt i 2)))
#+END_SRC

One could also try displaying the filesystem, clicking dragging and deleting images.

Show > Class Subclasses (then enter "t" at the prompt - without the quotes)

From Emacs: =M-x imaxima=

The 3D plotting demo can be found in [[./3d.lisp]]

lorenz t, nil axes t, nil animated-plot 0.3 and nil

See [[./system.org]] for more information.

use "e" while in dired to open the file under point in the browser

C-i to edit a text field in emacs, C-x # from emacs to switch back to
the browser

** Hacking Masamune
** Maxima

introduce to imaxima, introduce to plotting capabilities via gnuplot, and point out the problems with.

if you need live plotting, i.e. something with animation, hardware acceleration, need to do 3D work (CAD etc.) beyond whatever it is that can be done with GNUplot you should checkout 3d.lisp which contains the starting point and a discussion of how to go about sanely leveraging OpenGL to do these tasks on current hardware.

** CLIM

launch listener, try showing the vector 


All code is loaded into 

* Setup

For the time being the operator must manually enable a few niceties.

** Installing adblock



Jonas Kalderstam

Just a lone cowboy programmer...

Conkeror supports firefox addons to varying degrees. I found that a good indicator is if the addon has support for Firefox 3. This means you can use Adblock 2.0. But, the GUI for selecting a filter subscription will not show. Hence the need to install Adblock 1.3 first. To get Adblock up and running in Conkeror, do the following:

    In your rc-file, set:

session_pref("xpinstall.whitelist.required", false);  

    Go to Adblock versions.
    Install 1.3.10.
    Open extensions: M-x extensions.
    Go into preferences for Adblock and subscribe to a list, like
    Easylist. The list might complain about requiring Adblock 2 for some filters, which is fine since we will fix that next.
    Now go back and download/install version 2.0.1.
    Enjoy the web again.
 
I followed this guide with the modification of installing adblock 2.6.5
after installing versions 1.3.10 and 2.0.1 (which didn't let me subscribe to
filters).
 
Version info: binary 33.1 of XULrunner to launch Conkeror commit
48d3ef4369f267faf42451a580b1ac6bcb6a5a18, master branch of the repository
git://repo.or.cz/conkeror.git
 
to run: ~/path/to/xulrunner/xulrunner ~/path/to/conkeror/application.ini
 
make sure to subscribe to easylist in 2.6.5 or it won't work

Thanks to [[http://cowboyprogrammer.org/getting-adblock-to-work-in-conkeror/][Jonas Kalderstam]] for this tip.

** Installing the REPL

In Conkeror: M-x extensions, click "Install from file" from the wrench and
screwdriver icon in the top right and select:
 
~/quicklisp/local-projects/masamune/browser/mozrepl/mozrepl@hyperstruct.net.xpi

restart Conkeror. The parenscript repl should connect automatically. You
can kill it by removing the call from stumpwm::*timer-list*. If you 
restart Conkeror via `mm::start-conkeror' the repl will connect
automatically.

* Misc

output for the browser is located at ~/.masamune/browser-output. you can write to it via =dump("some-message");= try it using eval in conkeror using =M-:=


** TODO output for stumpwm located at ~/.masamune/stumpwm-output

file:///usr/share/maxima/5.18.1/doc/html/maxima_49.html#SEC212

The files emacs-customizations.el and lisp-customizations.lisp (in ~/quicklisp/local-projects/masamune) get loaded at the end of the init process and replace for your .emacs and .sbclrc files.

